package com.jzsk.model.mapper;

import com.jzsk.model.entity.TrDocument;

public interface TrDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    int deleteByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    int insert(TrDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    int insertSelective(TrDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    TrDocument selectByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    int updateByPrimaryKeySelective(TrDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    int updateByPrimaryKey(TrDocument record);
}