package com.jzsk.model.mapper;

import com.jzsk.model.entity.TrUser;

public interface TrUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    int insert(TrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    int insertSelective(TrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    TrUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    int updateByPrimaryKeySelective(TrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jan 08 15:39:18 CST 2019
     */
    int updateByPrimaryKey(TrUser record);
    
    TrUser selectByLoginName(String loginName);
}