package com.jzsk.filecode.model.entity;

import java.util.Date;

public class TrFilename {
    private String filenameId;

    private String filename;

    private String userId;

    private Date creteTime;
    
    private String filecode;
    

    public String getFilecode() {
		return filecode;
	}

	public void setFilecode(String filecode) {
		this.filecode = filecode;
	}

	public String getFilenameId() {
        return filenameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filename.filename_id
     *
     * @param filenameId the value for filename.filename_id
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public void setFilenameId(String filenameId) {
        this.filenameId = filenameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filename.filename
     *
     * @return the value of filename.filename
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filename.filename
     *
     * @param filename the value for filename.filename
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filename.user_id
     *
     * @return the value of filename.user_id
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filename.user_id
     *
     * @param userId the value for filename.user_id
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filename.crete_time
     *
     * @return the value of filename.crete_time
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public Date getCreteTime() {
        return creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filename.crete_time
     *
     * @param creteTime the value for filename.crete_time
     *
     * @mbggenerated Thu Jan 10 19:06:01 CST 2019
     */
    public void setCreteTime(Date creteTime) {
        this.creteTime = creteTime;
    }
}