package com.jzsk.filecode.model.entity;

public class TrFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_id
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_name
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_code
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    private String functionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_id
     *
     * @return the value of function.function_id
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_id
     *
     * @param functionId the value for function.function_id
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_name
     *
     * @return the value of function.function_name
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_name
     *
     * @param functionName the value for function.function_name
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_code
     *
     * @return the value of function.function_code
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_code
     *
     * @param functionCode the value for function.function_code
     *
     * @mbggenerated Thu Jan 10 19:06:26 CST 2019
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode;
    }
}