package com.jzsk.filecode.model.entity;

public class TrLog extends TrLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.namelog
     *
     * @mbggenerated Thu Jan 10 19:06:45 CST 2019
     */
    private String namelog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.namelog
     *
     * @return the value of log.namelog
     *
     * @mbggenerated Thu Jan 10 19:06:45 CST 2019
     */
    public String getNamelog() {
        return namelog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.namelog
     *
     * @param namelog the value for log.namelog
     *
     * @mbggenerated Thu Jan 10 19:06:45 CST 2019
     */
    public void setNamelog(String namelog) {
        this.namelog = namelog;
    }
}