package com.jzsk.filecode.model.entity;

import java.util.Date;

public class TrThree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.three_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String threeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.department
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.two_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String twoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.three_num
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private Integer threeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.three_version
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String threeVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.three_name
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String threeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.three_code
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String threeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.user_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column three.create_time
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.three_id
     *
     * @return the value of three.three_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getThreeId() {
        return threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.three_id
     *
     * @param threeId the value for three.three_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setThreeId(String threeId) {
        this.threeId = threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.department
     *
     * @return the value of three.department
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.department
     *
     * @param department the value for three.department
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.two_id
     *
     * @return the value of three.two_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getTwoId() {
        return twoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.two_id
     *
     * @param twoId the value for three.two_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setTwoId(String twoId) {
        this.twoId = twoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.three_num
     *
     * @return the value of three.three_num
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public Integer getThreeNum() {
        return threeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.three_num
     *
     * @param threeNum the value for three.three_num
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setThreeNum(Integer threeNum) {
        this.threeNum = threeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.three_version
     *
     * @return the value of three.three_version
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getThreeVersion() {
        return threeVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.three_version
     *
     * @param threeVersion the value for three.three_version
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setThreeVersion(String threeVersion) {
        this.threeVersion = threeVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.three_name
     *
     * @return the value of three.three_name
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getThreeName() {
        return threeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.three_name
     *
     * @param threeName the value for three.three_name
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setThreeName(String threeName) {
        this.threeName = threeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.three_code
     *
     * @return the value of three.three_code
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getThreeCode() {
        return threeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.three_code
     *
     * @param threeCode the value for three.three_code
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setThreeCode(String threeCode) {
        this.threeCode = threeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.user_id
     *
     * @return the value of three.user_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.user_id
     *
     * @param userId the value for three.user_id
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column three.create_time
     *
     * @return the value of three.create_time
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column three.create_time
     *
     * @param createTime the value for three.create_time
     *
     * @mbggenerated Thu Jun 20 16:32:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}