package com.jzsk.filecode.model.entity;

import java.util.Date;

public class TrThreetable {

    private String threetableId;

    private Integer threeNum;

    private Integer threetableNum;

    private String threetableVersion;

    private String threetableName;

    private String threetableCode;

    private String userId;

    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.threetable_id
     *
     * @return the value of threetable.threetable_id
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public String getThreetableId() {
        return threetableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.threetable_id
     *
     * @param threetableId the value for threetable.threetable_id
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreetableId(String threetableId) {
        this.threetableId = threetableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.three_num
     *
     * @return the value of threetable.three_num
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public Integer getThreeNum() {
        return threeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.three_num
     *
     * @param threeNum the value for threetable.three_num
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreeNum(Integer threeNum) {
        this.threeNum = threeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.threetable_num
     *
     * @return the value of threetable.threetable_num
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public Integer getThreetableNum() {
        return threetableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.threetable_num
     *
     * @param threetableNum the value for threetable.threetable_num
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreetableNum(Integer threetableNum) {
        this.threetableNum = threetableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.threetable_version
     *
     * @return the value of threetable.threetable_version
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public String getThreetableVersion() {
        return threetableVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.threetable_version
     *
     * @param threetableVersion the value for threetable.threetable_version
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreetableVersion(String threetableVersion) {
        this.threetableVersion = threetableVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.threetable_name
     *
     * @return the value of threetable.threetable_name
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public String getThreetableName() {
        return threetableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.threetable_name
     *
     * @param threetableName the value for threetable.threetable_name
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreetableName(String threetableName) {
        this.threetableName = threetableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.threetable_code
     *
     * @return the value of threetable.threetable_code
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public String getThreetableCode() {
        return threetableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.threetable_code
     *
     * @param threetableCode the value for threetable.threetable_code
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setThreetableCode(String threetableCode) {
        this.threetableCode = threetableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.user_id
     *
     * @return the value of threetable.user_id
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.user_id
     *
     * @param userId the value for threetable.user_id
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threetable.create_time
     *
     * @return the value of threetable.create_time
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threetable.create_time
     *
     * @param createTime the value for threetable.create_time
     *
     * @mbggenerated Tue Jan 22 14:36:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}