package com.jzsk.filecode.model.entity;

import java.util.Date;

public class TrTwotable {

	private String twotableId;
	private String department;
	private String twoId;
	private Integer tableNum;
	private String tableVersion;
	private String tableName;
	private String userId;
	private Date createTime;
	private String tableCode;

	public String getTableCode() {
		return tableCode;
	}

	public void setTableCode(String tableCode) {
		this.tableCode = tableCode;
	}

	public String getTwotableId() {
		return twotableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.twotable_id
	 *
	 * @param twotableId
	 *            the value for twotable.twotable_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setTwotableId(String twotableId) {
		this.twotableId = twotableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.department
	 *
	 * @return the value of twotable.department
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.department
	 *
	 * @param department
	 *            the value for twotable.department
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.two_id
	 *
	 * @return the value of twotable.two_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public String getTwoId() {
		return twoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.two_id
	 *
	 * @param twoId
	 *            the value for twotable.two_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setTwoId(String twoId) {
		this.twoId = twoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.table_num
	 *
	 * @return the value of twotable.table_num
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public Integer getTableNum() {
		return tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.table_num
	 *
	 * @param tableNum
	 *            the value for twotable.table_num
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setTableNum(Integer tableNum) {
		this.tableNum = tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.table_version
	 *
	 * @return the value of twotable.table_version
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public String getTableVersion() {
		return tableVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.table_version
	 *
	 * @param tableVersion
	 *            the value for twotable.table_version
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setTableVersion(String tableVersion) {
		this.tableVersion = tableVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.table_name
	 *
	 * @return the value of twotable.table_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.table_name
	 *
	 * @param tableName
	 *            the value for twotable.table_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.user_id
	 *
	 * @return the value of twotable.user_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.user_id
	 *
	 * @param userId
	 *            the value for twotable.user_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column twotable.create_time
	 *
	 * @return the value of twotable.create_time
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column twotable.create_time
	 *
	 * @param createTime
	 *            the value for twotable.create_time
	 *
	 * @mbggenerated Mon Jan 21 10:14:45 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}