package com.jzsk.filecode.model.entity;

import java.util.Date;

public class TrTwo {

	private String twoId;
	private String department;
	private String fileName;
	private String version;
	private String year;
	private String twoName;
	private Date createTime;
	private String userId;

	public String getTwoId() {
		return twoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.two_id
	 *
	 * @param twoId
	 *            the value for two.two_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setTwoId(String twoId) {
		this.twoId = twoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.department
	 *
	 * @return the value of two.department
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.department
	 *
	 * @param department
	 *            the value for two.department
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.file_name
	 *
	 * @return the value of two.file_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.file_name
	 *
	 * @param fileName
	 *            the value for two.file_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.version
	 *
	 * @return the value of two.version
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.version
	 *
	 * @param version
	 *            the value for two.version
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.year
	 *
	 * @return the value of two.year
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.year
	 *
	 * @param year
	 *            the value for two.year
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.two_name
	 *
	 * @return the value of two.two_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getTwoName() {
		return twoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.two_name
	 *
	 * @param twoName
	 *            the value for two.two_name
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setTwoName(String twoName) {
		this.twoName = twoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.create_time
	 *
	 * @return the value of two.create_time
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.create_time
	 *
	 * @param createTime
	 *            the value for two.create_time
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column two.user_id
	 *
	 * @return the value of two.user_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column two.user_id
	 *
	 * @param userId
	 *            the value for two.user_id
	 *
	 * @mbggenerated Mon Jan 21 10:14:19 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

}