package com.jzsk.filecode.model.entity;

public class TrType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_id
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_code
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_name
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_id
     *
     * @return the value of type.type_id
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_id
     *
     * @param typeId the value for type.type_id
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_code
     *
     * @return the value of type.type_code
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_code
     *
     * @param typeCode the value for type.type_code
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_name
     *
     * @return the value of type.type_name
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_name
     *
     * @param typeName the value for type.type_name
     *
     * @mbggenerated Thu Jan 10 19:07:34 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}