package com.jzsk.model.entity;

public class TrDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.document_id
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    private String documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.document_name
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    private String documentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.document_code
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    private String documentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.document_id
     *
     * @return the value of document.document_id
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.document_id
     *
     * @param documentId the value for document.document_id
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.document_name
     *
     * @return the value of document.document_name
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.document_name
     *
     * @param documentName the value for document.document_name
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.document_code
     *
     * @return the value of document.document_code
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public String getDocumentCode() {
        return documentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.document_code
     *
     * @param documentCode the value for document.document_code
     *
     * @mbggenerated Tue Jan 08 15:36:59 CST 2019
     */
    public void setDocumentCode(String documentCode) {
        this.documentCode = documentCode;
    }
}